120 chapter 1 provide overview over the upcoming chapters
vantage6/vantage6-workshop pull request #129
Opened 2024-09-25 14:40 UTC by dsmits

2024-09-26 12:24 UTC, wbaccinelli requested changes
I think it would be nicer having the overview of all course at the beginning of chapter 1 instead of at the end.

2024-10-01 09:03 UTC, frankcorneliusmartin approved these changes
Approved with a minor suggestion.

2024-10-01 09:03 UTC, frankcorneliusmartin commented on episodes/chap1_introduction_FL.md
> +In the second part of the workshop, we will shift focus  to interacting with vantage6 through Python, bypassing the UI. We will also delve into creating a federated algorithm using the platform's alg
```suggestion
In the second part of the workshop, we will shift focus to interacting with vantage6 using Python, taking the place of the UI. We will also delve into creating a federated algorithm using the platform's algorithm tools.
```

2024-10-01 13:51 UTC, wbaccinelli approved these changes

2024-10-01 13:52 UTC, merged